# Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

def get_exp() :
    terms = [a ** b for a in range(2,101) for b in range(2,101)]
    distinct_terms = set(terms)
    return len(distinct_terms)

print(get_exp())
